create table if not exists public.result_snapshots (
  id bigint generated by default as identity primary key,
  election_code text not null,
  office text not null,
  scope text not null,
  source_url text not null,
  idg text,
  generated_date text,
  generated_time text,
  sections_percentage numeric(12,9) default 0,
  payload jsonb not null,
  inserted_at timestamptz not null default now(),
  unique (source_url, idg)
);

create index if not exists result_snapshots_lookup_idx
  on public.result_snapshots (election_code, office, scope, inserted_at desc);

alter table public.result_snapshots enable row level security;

revoke all on table public.result_snapshots from anon, authenticated;

comment on table public.result_snapshots is
  'Snapshots dos arquivos oficiais de resultado do TSE usados pelo ApuraBrasil. Escrita somente pelo backend com service role.';
