const AdmZip=require('adm-zip');
const {parse}=require('csv-parse/sync');

const SOURCES={
  '2022-president-1':'https://cdn.tse.jus.br/estatistica/sead/eleicoes/eleicoes2022/Historico_Totalizacao_Presidente_BR_1T_2022.zip',
  '2022-president-2':'https://cdn.tse.jus.br/estatistica/sead/eleicoes/eleicoes2022/Historico_Totalizacao_Presidente_BR_2T_2022.zip'
};
const cache=new Map();
function send(res,status,payload,cacheHeader='public, s-maxage=86400, stale-while-revalidate=604800'){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control',cacheHeader);res.setHeader('Access-Control-Allow-Origin','*');res.end(JSON.stringify(payload));}
async function fetchBuffer(url,timeout=90000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':'ApuraBrasil/0.3 (+Vercel)'}});if(!r.ok)throw new Error(`TSE respondeu ${r.status}`);return Buffer.from(await r.arrayBuffer());}finally{clearTimeout(t);}}
function decode(data){let text=data.toString('latin1');if(!/;/.test(text.slice(0,1000)))text=data.toString('utf8');return text;}
async function load(year,office,round){const key=`${year}-${office}-${round}`,hit=cache.get(key);if(hit)return hit;const url=SOURCES[key];if(!url)throw new Error('Arquivo histórico ainda não integrado.');const buffer=await fetchBuffer(url),zip=new AdmZip(buffer),entry=zip.getEntries().find(e=>!e.isDirectory&&/\.csv$/i.test(e.entryName))||zip.getEntries().find(e=>!e.isDirectory);if(!entry)throw new Error('Arquivo histórico do TSE sem CSV.');const rows=parse(decode(entry.getData()),{columns:true,delimiter:';',quote:'"',skip_empty_lines:true,relax_column_count:true,relax_quotes:true,bom:true,trim:true});const value={url,entry:entry.entryName,rows};cache.set(key,value);return value;}
function number(v){const n=Number(String(v??'').replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0;}
function percentFraction(v){const n=number(v);return n<=1?n*100:n;}
function pretty(prefix){return String(prefix||'').replace(/_/g,' ').replace(/\s+/g,' ').trim();}
function finalRow(rows){let best=null,bestSections=-1;for(const row of rows){const sections=number(row.QT_SECOES_TOT_ACUMULADO);if(sections>=bestSections){best=row;bestSections=sections;}}return best||rows[rows.length-1]||{};}
function candidatesFromWide(row){const suffix='_QT_VOTOS_TOT_ACUMULADO',excluded=new Set(['BRANCO','NULO']);const out=[];for(const key of Object.keys(row)){if(!key.endsWith(suffix))continue;const prefix=key.slice(0,-suffix.length);if(!prefix||excluded.has(prefix)||prefix==='QT_VOTOS_TOTAL'||prefix==='QT_VOTOS_CONCORRENTES')continue;const votes=number(row[key]),pctKey=`${prefix}_PE_VOTOS_TOT_ACUMULADO`;out.push({number:'',sequence:'',name:pretty(prefix),ballotName:pretty(prefix),party:'',coalition:'',votes,percentage:percentFraction(row[pctKey]),status:'',electedFlag:'',photoUrl:''});}return out.sort((a,b)=>b.votes-a.votes||a.ballotName.localeCompare(b.ballotName,'pt-BR'));}
function summarize(rows,year,round,sourceUrl){if(!rows.length)return null;const row=finalRow(rows),totalSections=number(row.QT_SECOES_TOTAL),totalized=number(row.QT_SECOES_TOT_ACUMULADO),sectionsPct=percentFraction(row.PE_SECOES_TOT_ACUMULADO),electorate=number(row.QT_APTOS_TOTAL),turnout=number(row.QT_VOTOS_TOTAL_ACUMULADO),valid=number(row.QT_VOTOS_CONCORRENTES_ACUMULADO),blank=number(row.BRANCO_QT_VOTOS_TOT_ACUMULADO),nullVotes=number(row.NULO_QT_VOTOS_TOT_ACUMULADO),abstentions=Math.max(0,electorate-turnout),stamp=String(row.DT_TOTALIZACAO||''),[date,time]=stamp.split(/\s+/,2),candidates=candidatesFromWide(row);return{ok:true,available:true,archive:true,future:false,year,electionType:'geral',round,office:'presidente',officeLabel:'Presidente',scope:'BR',final:totalSections>0&&totalized>=totalSections,generatedDate:date||stamp,generatedTime:time||'',sections:{total:totalSections,totalized,percentage:sectionsPct||((totalSections&&totalized)?totalized/totalSections*100:0)},electorate:{total:electorate,turnout,turnoutPercentage:electorate?turnout/electorate*100:0,abstentions,abstentionPercentage:electorate?abstentions/electorate*100:0},votes:{valid,validPercentage:turnout?valid/turnout*100:0,blank,blankPercentage:percentFraction(row.BRANCO_PE_VOTOS_TOT_ACUMULADO),null:nullVotes,nullPercentage:percentFraction(row.NULO_PE_VOTOS_TOT_ACUMULADO)},candidates,groups:[],sourceUrl,historicalSnapshot:stamp,checkedAt:new Date().toISOString()};}
module.exports=async function handler(req,res){try{const year=Number(req.query?.year||2022),office=String(req.query?.office||'president'),round=Number(req.query?.round||2);if(year!==2022||office!=='president')return send(res,200,{ok:true,available:false,archive:true,year,notice:'Arquivo histórico ainda não integrado.'});const data=await load(year,office,round);if(String(req.query?.debug||'')==='1')return send(res,200,{ok:true,url:data.url,entry:data.entry,rowCount:data.rows.length,columns:Object.keys(data.rows[0]||{}),sample:data.rows.slice(0,3)},'no-store');return send(res,200,summarize(data.rows,year,round,data.url));}catch(error){return send(res,502,{ok:false,error:'Não foi possível carregar o arquivo histórico do TSE.',detail:error.message},'no-store');}};