const AdmZip=require('adm-zip');
const {parse}=require('csv-parse/sync');

const SOURCES={
  '2022-president-1': 'https://cdn.tse.jus.br/estatistica/sead/eleicoes/eleicoes2022/Historico_Totalizacao_Presidente_BR_1T_2022.zip',
  '2022-president-2': 'https://cdn.tse.jus.br/estatistica/sead/eleicoes/eleicoes2022/Historico_Totalizacao_Presidente_BR_2T_2022.zip'
};
let cache=new Map();
function send(res,status,payload,cacheHeader='public, s-maxage=86400, stale-while-revalidate=604800'){res.statusCode=status;res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control',cacheHeader);res.setHeader('Access-Control-Allow-Origin','*');res.end(JSON.stringify(payload));}
async function fetchBuffer(url,timeout=90000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,headers:{'User-Agent':'ApuraBrasil/0.3 (+Vercel)'}});if(!r.ok)throw new Error(`TSE respondeu ${r.status}`);return Buffer.from(await r.arrayBuffer());}finally{clearTimeout(t);}}
function decode(data){let text=data.toString('latin1');if(!/;/.test(text.slice(0,1000)))text=data.toString('utf8');return text;}
async function load(year,office,round){const key=`${year}-${office}-${round}`;const hit=cache.get(key);if(hit)return hit;const url=SOURCES[key];if(!url)throw new Error('Arquivo histórico ainda não integrado.');const buffer=await fetchBuffer(url);const zip=new AdmZip(buffer);const entry=zip.getEntries().find(e=>!e.isDirectory&&/\.csv$/i.test(e.entryName))||zip.getEntries().find(e=>!e.isDirectory);if(!entry)throw new Error('Arquivo histórico do TSE sem CSV.');const text=decode(entry.getData());const rows=parse(text,{columns:true,delimiter:';',quote:'"',skip_empty_lines:true,relax_column_count:true,relax_quotes:true,bom:true,trim:true});const value={url,entry:entry.entryName,rows};cache.set(key,value);return value;}
function norm(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/[^A-Z0-9]+/g,'_').replace(/^_+|_+$/g,'');}
function pick(row,names){const keys=Object.keys(row);for(const name of names){if(row[name]!==undefined&&String(row[name]).trim()!=='')return row[name];const target=norm(name),k=keys.find(x=>norm(x)===target);if(k&&String(row[k]).trim()!=='')return row[k];}return'';}
function number(v){const n=Number(String(v??'').replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?n:0;}
function dateKey(row){const d=String(pick(row,['DT_HORA','DT_GERACAO','DATA_HORA','DT_TOTALIZACAO','DT_CARGA']));const h=String(pick(row,['HH_HORA','HH_GERACAO','HORA','HH_TOTALIZACAO']));return`${d} ${h}`.trim();}
function summarize(rows,year,round){if(!rows.length)return null;const debugCols=Object.keys(rows[0]);const timeKeys=[...new Set(rows.map(dateKey).filter(Boolean))];const latest=timeKeys[timeKeys.length-1]||'';let selected=latest?rows.filter(r=>dateKey(r)===latest):rows;const candidateNameFields=['NM_CANDIDATO','NM_URNA_CANDIDATO','NM_CANDIDATO_URNA','NM_CANDIDATO_TOTALIZACAO'];const voteFields=['QT_VOTOS','QT_VOTOS_NOMINAIS','QT_VOTOS_CANDIDATO','QT_VOTOS_TOTALIZADOS','VAP'];const pctFields=['PC_VOTOS','PCT_VOTOS','PERCENTUAL_VOTOS','PVAP'];const numFields=['NR_CANDIDATO','NUMERO_CANDIDATO'];const partyFields=['SG_PARTIDO','SIGLA_PARTIDO'];const statusFields=['DS_SIT_TOT_TURNO','DS_SITUACAO_CANDIDATO_TURNO','DS_SITUACAO_TOTALIZACAO'];const candidates=[];const seen=new Set();for(const row of selected){const name=String(pick(row,candidateNameFields)).trim();if(!name)continue;const numberText=String(pick(row,numFields)).trim(),id=`${numberText}|${name}`;if(seen.has(id))continue;seen.add(id);candidates.push({number:numberText,name,ballotName:name,party:String(pick(row,partyFields)).trim(),votes:number(pick(row,voteFields)),percentage:number(pick(row,pctFields)),status:String(pick(row,statusFields)).trim(),electedFlag:''});}
candidates.sort((a,b)=>b.votes-a.votes||a.ballotName.localeCompare(b.ballotName,'pt-BR'));const first=selected[0]||{};const totalSections=number(pick(first,['QT_SECOES','QT_SECOES_TOTAL','QT_SECOES_ELEICAO','QT_SECOES_TOTALIZAVEIS']));const totalized=number(pick(first,['QT_SECOES_TOTALIZADAS','QT_SECOES_APURADAS','QT_SECOES_COMPUTADAS']));const pctSections=number(pick(first,['PC_SECOES_TOTALIZADAS','PCT_SECOES_TOTALIZADAS','PST']));return{ok:true,available:true,archive:true,future:false,year,electionType:'geral',round,office:'presidente',officeLabel:'Presidente',scope:'BR',final:true,generatedDate:String(pick(first,['DT_GERACAO','DT_TOTALIZACAO'])),generatedTime:String(pick(first,['HH_GERACAO','HH_TOTALIZACAO'])),sections:{total:totalSections,totalized,percentage:pctSections||((totalSections&&totalized)?totalized/totalSections*100:100)},electorate:{total:number(pick(first,['QT_ELEITORADO','QT_ELEITORES','QT_ELEITOR'])),turnout:number(pick(first,['QT_COMPARECIMENTO','QT_ELEITORES_COMPARECIMENTO'])),turnoutPercentage:number(pick(first,['PC_COMPARECIMENTO','PCT_COMPARECIMENTO'])),abstentions:number(pick(first,['QT_ABSTENCOES','QT_ABSTENCAO'])),abstentionPercentage:number(pick(first,['PC_ABSTENCOES','PCT_ABSTENCAO']))},votes:{valid:number(pick(first,['QT_VOTOS_VALIDOS','QT_VOTOS_VALIDOS_CAND'])),validPercentage:number(pick(first,['PC_VOTOS_VALIDOS'])),blank:number(pick(first,['QT_VOTOS_BRANCOS'])),blankPercentage:number(pick(first,['PC_VOTOS_BRANCOS'])),null:number(pick(first,['QT_VOTOS_NULOS'])),nullPercentage:number(pick(first,['PC_VOTOS_NULOS']))},candidates,groups:[],sourceUrl:SOURCES[`${year}-president-${round}`],historicalSnapshot:latest,debugColumns:debugCols,checkedAt:new Date().toISOString()};}
module.exports=async function handler(req,res){try{const year=Number(req.query?.year||2022),office=String(req.query?.office||'president'),round=Number(req.query?.round||1);if(year!==2022||office!=='president')return send(res,200,{ok:true,available:false,archive:true,year,notice:'Arquivo histórico ainda não integrado.'});const data=await load(year,office,round);if(String(req.query?.debug||'')==='1')return send(res,200,{ok:true,url:data.url,entry:data.entry,rowCount:data.rows.length,columns:Object.keys(data.rows[0]||{}),sample:data.rows.slice(0,3)},'no-store');const result=summarize(data.rows,year,round);delete result.debugColumns;return send(res,200,result);}catch(error){return send(res,502,{ok:false,error:'Não foi possível carregar o arquivo histórico do TSE.',detail:error.message},'no-store');}};